@extends('layouts.html')

@section('tittle', 'Home')

@section('imports')
    @vite('resources/css/complements/all.css')
@endsection

@section('content')
@component('_components.header')@endcomponent

    <h1>Hola presidente | Home2</h1>

    <h1>Hola presidente | Home1asdasd</h1>
    <h1>Hola presidente | Home1asdasd</h1>
    <h1>Hola presidente | Home1a</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>
    <h1>Hola presidente | Home1</h1>

@endsection
